description: "Baseline"
seed: !!int 0
device: "cpu"
num_workers: !!int 4
hparams:
  batch_size: !!int 32
  num_epochs: !!int 3
  lr: !!float 1e-3
  weight_decay: !!float 1e-4
model:
  name: "ExampleModel"
  params:
    feature_size: !!int 16
    num_stages: !!int 4
    num_classes: !!int 100
optimizer:
  name: "AdamW"
  params:
    lr: ${hparams.lr}  # OmegaConf variable interpolation.
    weight_decay: ${hparams.weight_decay}  # OmegaConf variable interpolation.
scheduler:
  name: OneCycleLR
  params:
    max_lr: ${optimizer.params.lr}  # OmegaConf variable interpolation.
    pct_start: !!float 0.33
    div_factor: !!float 1e3
    final_div_factor: !!float 1e4
loss_fn:
  name: "CrossEntropyLoss"